### ISSUE TITLE
Problem with typescript import

### ISSUE THREAD

**Issue by Chklang** [Neamar/auto-load#13]
If i do
import * as autoload from 'auto-load';
i've an error "It's not a module".

I've modified your index.d.ts to :
```
declare module autoload {
}
declare type ModuleExports = any;
declare type AutoloadTree = {
    [key: string]: AutoloadTree | ModuleExports
};

declare interface AutoloadOptions {
    deep?: boolean,
    js?: boolean,
    json?: boolean
}

declare function autoload(baseDirectory: string, options?: AutoloadOptions): AutoloadTree;

export = autoload;
```
and it's works (i've moved to "}" from end to start to do "module autoload {}" and rename "auto-load" to "autoload").

I can't fork/commit/push because github isn't open from my company :(

Regards

**Comment by Chklang** [comment]
Can you do a thing about it?

I must do "const autoload = require("auto-load");" to import your lib in typescript.

Regards

**Comment by danpantry** [comment]
HI @Chklang can I get some more information? I cannot reproduce your issue using TypeScript 2.8.3.

What version of TypeScript are you using?

Note that as this is a CommonJS module you should import it using `import autoload = require('auto-load')` in TS rather than `import autoload from 'auto-load'` (although you would see TS2497 which is not the same error you cite).

**Comment by delphin-germa-orange** [comment]
Yeah thank you! The problem is gone! \o/

**Comment by Chklang** [comment]
Yeah thank you! The problem is gone! \o/
