### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by franciscop** [Neamar/auto-load#3]
Is it possible to have relative paths, or absolute to the root, for auto-load? So it becomes easier to just include a full directory. Example:

```js
// Relative to the root
var models = require('auto-load')('models');

// Or relative to the current file
var models = require('auto-load')('../models');
```

Currently the only way to do this is to use a more cumbersome notation:

```js
var models = require('auto-load')(__dirname + '/../models');
```

[This question in StackOverflow](http://stackoverflow.com/q/13488501/938236) illustrates the issue perfectly, as it's also about readdirSync(), which is used in auto-load.

Note: I'm just proposing it since I had a really similar personal package, until I decided to find one pre-made and found this one. This is basically the only difference so I'm proposing it for improvement, but of course there's no problem typing 15-16 characters more.

**Comment by Neamar** [comment]
It's an interesting idea (and in fact I wasn't aware fs.read uses process.cwd by default, very interesting read).

I'm personally more used to (and prefer) the `require` way of being dependant to the current file; seems more logical to me since we use `require` way more often than `fs`. Plus, keeping track of `cwd` is tricky at best, and cumbersome at worst, leading to complex situations on some bash scripts.

So.... yes, i'm ok for a `require`-like import! If you have time for this, I'll merge any PR quickly and publish an updated package. Else, I'll probably find some time to do this later in the month!

**Comment by Neamar** [comment]
Hum, thinking back on this.

Reason I made it this way on the first run is the auto-load code does not know which file called it, and is unable to resolve the path according to the parent's filepath.

Just had a look at the real `require` code on https://github.com/nodejs/node-v0.x-archive/blob/069dd07a1732c6a752773aaed9e8c18ab472375f/lib/module.js#L355: it looks like they have a `this` context available giving them more information on the current filename.

Unfortunately, we don't have this kind of information on auto-load. The only way I can think of retrieving the original source path of the caller would be to create a `new Errror()` and manually parse the stack trace. Which seems ugly (more ugly than using __dirname at least ;))

Some links on stackoverflow with the same question and sadly no good answer:

* http://stackoverflow.com/questions/13227489/how-can-one-get-the-file-path-of-the-caller-function-in-node-js
* http://stackoverflow.com/questions/9475792/how-does-require-in-node-js-work
* http://stackoverflow.com/questions/16697791/nodejs-get-filename-of-caller-function

**Comment by franciscop** [comment]
I can see the issue on hand and also couldn't find a solution. However I could implement one relative to the root [in this pull request](https://github.com/Neamar/auto-load/pull/4).
