### ISSUE TITLE
More file types

### ISSUE THREAD

**Issue by franciscop** [Neamar/auto-load#6]
Following [the discussion here](https://github.com/Neamar/auto-load/issues/5), it might be interesting to load more file types with `auto-load`. I open this issue to discuss whether this is within the scope of auto-loader or would be better suited for a package that uses auto-loader. For a folder containing the following files:

```
config.json
README.md
script.js
data.txt
LICENSE
hello.txt
```

Would it make sense to load more than just `config.json` and `script.js`? The following is proposed:

```js
var files = require('auto-load')('files', { extensions: ['txt'] });
```

This would load the files with the extensions `.txt` and load them as strings. Only `.js` and `.json` are parsed, while other files are loaded as strings.

## Pros
- Filter by js or json in case we only want one.
- Easy to load any kind of file with a known syntax.
- More according to the name (auto-load could load anything, while [require-all](https://github.com/felixge/node-require-all) might have been better suited).

## Cons
- Inconsistent. While one file is loaded in one way, the other is loaded in a different way.
- The library would become a bit **bloated**.
- Multi-purpose for the library

**Comment by Neamar** [comment]
Right. As you say, auto-load is probably not perfectly named, since it's only doing `require` for now.

I think however that auto-load should not try to do too much.

First problem: parsing vs. reading. This is tricky, and can be hard to understand for most users (is it an object or a string? How can i know? What happens if i have a readme.js and a readme.md file?)

Plus, it would probably means using fs.readFileSync() a lot (since adding async would clearly bloat usage)

Second problem: syntax can be complex. The "sane" default would be to load all files, but this will be a very bad solutions as soon as the user put some pictures or a .git in the directory...

If I were to sum up my thoughts as of now, I think we should add in auyto-load a js / json flag to restrict  require's (but only in js/json land, no more).

Loading a txt or other files would not be part of the lib, since it can be done with a simple for / loop and `fs.*Sync` functions -- or maybe another package, based on this one as you implied?
